### ISSUE TITLE
PSQL Array to string conversion

### ISSUE THREAD

**Issue by psjbeisler** [LycheeOrg/Lychee-Laravel#186]
**Something went wrong, error , Array to string conversion**

Failing to upload files
Fresh install
Postgresql database with clean migrate:status

```
2019-04-11 05:39:43 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/small/3b263686119b680f7016d3f23ed4fa78.jpg
2019-04-11 05:39:43 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/3b263686119b680f7016d3f23ed4fa78.jpg
2019-04-11 05:39:42 -- notice -- App\ModelFunctions\PhotoFunctions::add -- 343 -- 3b263686119b680f7016d3f23ed4fa78.jpeg
2019-04-11 05:39:42 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/3b263686119b680f7016d3f23ed4fa78@2x.jpeg
2019-04-11 05:39:42 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/3b263686119b680f7016d3f23ed4fa78.jpeg
2019-04-11 05:39:42 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 100 -- Photo URL is 3b263686119b680f7016d3f23ed4fa78.jpg
2019-04-11 05:39:41 -- error -- App\ModelFunctions\PhotoFunctions::save -- 479 -- Something went wrong, error , Array to string conversion (SQL: insert into "photos" ("id", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "public", "owner_id", "star", "checksum", "album_id", "thumb2x", "thumbUrl", "medium", "small", "updated_at", "created_at") values (15549611804551, IMG_20150115_224548_1, 4cfee02635c19c202b8cb2c3b402603f.jpg, , , 2592, 1944, image/jpeg, 1.9 MB, 640, f/2.8, Samsung, Galaxy Nexus, , 59994/1000000 s, 3.4 mm, 2015-01-15 22:45:48, , , , 0, 0, 0, 99868c5e41c114e428f24004ff8c2811fd53415a, 15549611226882, 1, 4cfee02635c19c202b8cb2c3b402603f.jpeg, 1440x1080, 480x360, 2019-04-11 05:39:41, 2019-04-11 05:39:41) returning "id")
2019-04-11 05:39:41 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/small/4cfee02635c19c202b8cb2c3b402603f.jpg
2019-04-11 05:39:41 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/4cfee02635c19c202b8cb2c3b402603f.jpg
2019-04-11 05:39:41 -- notice -- App\ModelFunctions\PhotoFunctions::add -- 343 -- 4cfee02635c19c202b8cb2c3b402603f.jpeg
2019-04-11 05:39:41 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/4cfee02635c19c202b8cb2c3b402603f@2x.jpeg
2019-04-11 05:39:40 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/4cfee02635c19c202b8cb2c3b402603f.jpeg
2019-04-11 05:39:40 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 100 -- Photo URL is 4cfee02635c19c202b8cb2c3b402603f.jpg
2019-04-11 05:39:38 -- error -- App\ModelFunctions\PhotoFunctions::save -- 479 -- Something went wrong, error , Array to string conversion (SQL: insert into "photos" ("id", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "public", "owner_id", "star", "checksum", "album_id", "thumb2x", "thumbUrl", "medium", "small", "updated_at", "created_at") values (15549611777580, IMG_20140725_190218, 6e1b1c6dbe4dd2c573988e9e8f40bced.jpg, , , 1944, 2592, image/jpeg, 1016.5 KB, 100, f/2.8, Samsung, Galaxy Nexus, , 59994/1000000 s, 3.4 mm, 2014-07-25 19:02:18, , , , 0, 0, 0, ec2674c07f01e86dff48cbe82ef6ddbfc79ede8c, 15549611226882, 1, 6e1b1c6dbe4dd2c573988e9e8f40bced.jpeg, 810x1080, 270x360, 2019-04-11 05:39:38, 2019-04-11 05:39:38) returning "id")
2019-04-11 05:39:38 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/small/6e1b1c6dbe4dd2c573988e9e8f40bced.jpg
2019-04-11 05:39:38 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/6e1b1c6dbe4dd2c573988e9e8f40bced.jpg
2019-04-11 05:39:38 -- notice -- App\ModelFunctions\PhotoFunctions::add -- 343 -- 6e1b1c6dbe4dd2c573988e9e8f40bced.jpeg
2019-04-11 05:39:38 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/6e1b1c6dbe4dd2c573988e9e8f40bced@2x.jpeg
2019-04-11 05:39:38 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/6e1b1c6dbe4dd2c573988e9e8f40bced.jpeg
2019-04-11 05:39:37 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 100 -- Photo URL is 6e1b1c6dbe4dd2c573988e9e8f40bced.jpg
2019-04-11 05:39:37 -- error -- App\ModelFunctions\PhotoFunctions::save -- 479 -- Something went wrong, error , Array to string conversion (SQL: insert into "photos" ("id", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "public", "owner_id", "star", "checksum", "album_id", "thumb2x", "thumbUrl", "medium", "small", "updated_at", "created_at") values (15549611764372, IMG_20140416_230210, 284c95c31c14772228db814ea13f14b7.jpg, , , 2592, 1944, image/jpeg, 878.6 KB, 640, f/2.8, Samsung, Galaxy Nexus, , 58322/1000000 s, 3.4 mm, 2014-04-16 23:02:10, , , , 0, 0, 0, fc27e250541400d0b93f31c46e30d4664d6eed14, 15549611226882, 1, 284c95c31c14772228db814ea13f14b7.jpeg, 1440x1080, 480x360, 2019-04-11 05:39:37, 2019-04-11 05:39:37) returning "id")
2019-04-11 05:39:37 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/small/284c95c31c14772228db814ea13f14b7.jpg
2019-04-11 05:39:37 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/284c95c31c14772228db814ea13f14b7.jpg
2019-04-11 05:39:37 -- notice -- App\ModelFunctions\PhotoFunctions::add -- 343 -- 284c95c31c14772228db814ea13f14b7.jpeg
2019-04-11 05:39:37 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/284c95c31c14772228db814ea13f14b7@2x.jpeg
2019-04-11 05:39:36 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/284c95c31c14772228db814ea13f14b7.jpeg
2019-04-11 05:39:36 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 100 -- Photo URL is 284c95c31c14772228db814ea13f14b7.jpg
```

**Comment by ildyria** [comment]
Can you pull what I just pushed and try again ? 
The error code was not showing, it hopefully should be fixed now.

**Comment by psjbeisler** [comment]
the page wouldnt even load until i did a `migrate:fresh` but even then, i get something similar after

`
2019-04-12 04:23:16 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/452004e6a9a243d714a1172054b6e757@2x.jpeg
    2019-04-12 04:23:15 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 101 -- Photo URL is 48006823d3260010ac55b267305f6e0b.jpg
    2019-04-12 04:23:15 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/452004e6a9a243d714a1172054b6e757.jpeg
    2019-04-12 04:23:14 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 101 -- Photo URL is 452004e6a9a243d714a1172054b6e757.jpg
    2019-04-12 04:23:14 -- error -- App\ModelFunctions\PhotoFunctions::save -- 480 -- Something went wrong, error 0, Array to string conversion (SQL: insert into "photos" ("id", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "public", "owner_id", "star", "checksum", "album_id", "thumb2x", "thumbUrl", "medium", "small", "updated_at", "created_at") values (15550429934893, IMG_20150115_224548_1, 1bf70c4a3430ad28033aed2b39a28611.jpg, , , 2592, 1944, image/jpeg, 1.9 MB, 640, f/2.8, Samsung, Galaxy Nexus, , 59994/1000000 s, 3.4 mm, 2015-01-15 22:45:48, , , , 0, 0, 0, 99868c5e41c114e428f24004ff8c2811fd53415a, 15550429810009, 1, 1bf70c4a3430ad28033aed2b39a28611.jpeg, 1440x1080, 480x360, 2019-04-12 04:23:14, 2019-04-12 04:23:14) returning "id")
    2019-04-12 04:23:14 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/small/1bf70c4a3430ad28033aed2b39a28611.jpg
    2019-04-12 04:23:14 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/1bf70c4a3430ad28033aed2b39a28611.jpg
    2019-04-12 04:23:14 -- notice -- App\ModelFunctions\PhotoFunctions::add -- 345 -- 1bf70c4a3430ad28033aed2b39a28611.jpeg
    2019-04-12 04:23:14 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/1bf70c4a3430ad28033aed2b39a28611@2x.jpeg
    2019-04-12 04:23:13 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/1bf70c4a3430ad28033aed2b39a28611.jpeg
    2019-04-12 04:23:13 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 101 -- Photo URL is 1bf70c4a3430ad28033aed2b39a28611.jpg
    2019-04-12 04:23:11 -- error -- App\ModelFunctions\PhotoFunctions::save -- 480 -- Something went wrong, error 0, Array to string conversion (SQL: insert into "photos" ("id", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "public", "owner_id", "star", "checksum", "album_id", "thumb2x", "thumbUrl", "medium", "small", "updated_at", "created_at") values (15550429906233, IMG_20140725_190218, 3a24b082bf9387f3cc56398976bbae6f.jpg, , , 1944, 2592, image/jpeg, 1016.5 KB, 100, f/2.8, Samsung, Galaxy Nexus, , 59994/1000000 s, 3.4 mm, 2014-07-25 19:02:18, , , , 0, 0, 0, ec2674c07f01e86dff48cbe82ef6ddbfc79ede8c, 15550429810009, 1, 3a24b082bf9387f3cc56398976bbae6f.jpeg, 810x1080, 270x360, 2019-04-12 04:23:11, 2019-04-12 04:23:11) returning "id")
    2019-04-12 04:23:11 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/small/3a24b082bf9387f3cc56398976bbae6f.jpg
    2019-04-12 04:23:11 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/3a24b082bf9387f3cc56398976bbae6f.jpg
    2019-04-12 04:23:11 -- notice -- App\ModelFunctions\PhotoFunctions::add -- 345 -- 3a24b082bf9387f3cc56398976bbae6f.jpeg
    2019-04-12 04:23:11 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/3a24b082bf9387f3cc56398976bbae6f@2x.jpeg
    2019-04-12 04:23:10 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/3a24b082bf9387f3cc56398976bbae6f.jpeg
    2019-04-12 04:23:10 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 101 -- Photo URL is 3a24b082bf9387f3cc56398976bbae6f.jpg
    2019-04-12 04:23:10 -- error -- App\ModelFunctions\PhotoFunctions::save -- 480 -- Something went wrong, error 0, Array to string conversion (SQL: insert into "photos" ("id", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "public", "owner_id", "star", "checksum", "album_id", "thumb2x", "thumbUrl", "medium", "small", "updated_at", "created_at") values (15550429892454, IMG_20140416_230210, a1e855d97f64461460843415b30213e1.jpg, , , 2592, 1944, image/jpeg, 878.6 KB, 640, f/2.8, Samsung, Galaxy Nexus, , 58322/1000000 s, 3.4 mm, 2014-04-16 23:02:10, , , , 0, 0, 0, fc27e250541400d0b93f31c46e30d4664d6eed14, 15550429810009, 1, a1e855d97f64461460843415b30213e1.jpeg, 1440x1080, 480x360, 2019-04-12 04:23:10, 2019-04-12 04:23:10) returning "id")
    2019-04-12 04:23:10 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/small/a1e855d97f64461460843415b30213e1.jpg
    2019-04-12 04:23:10 -- notice -- App\Image\ImagickHandler::scale -- 50 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/a1e855d97f64461460843415b30213e1.jpg
    2019-04-12 04:23:10 -- notice -- App\ModelFunctions\PhotoFunctions::add -- 345 -- a1e855d97f64461460843415b30213e1.jpeg
    2019-04-12 04:23:10 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/a1e855d97f64461460843415b30213e1@2x.jpeg
    2019-04-12 04:23:09 -- notice -- App\Image\ImagickHandler::crop -- 87 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/a1e855d97f64461460843415b30213e1.jpeg
    2019-04-12 04:23:09 -- notice -- App\ModelFunctions\PhotoFunctions::createThumb -- 101 -- Photo URL is a1e855d97f64461460843415b30213e1.jpg
`

**Comment by ildyria** [comment]
Sorry I fucked up with the last commit. I missed an edge case and the test suite did not catch it. :(

**Comment by psjbeisler** [comment]
getting duplicates currently
```2019-06-15 02:35:32 -- notice  -- App\Photo::predelete -- 339 -- 15605660337655 is a duplicate!```
 and still get the same error after an update; maybe its just the meta data in those photos? idk
``` 2019-06-15 02:33:35 -- notice  -- App\Image\ImagickHandler::scale -- 46 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/997c73f21ef31f7732aaea41b6413ed1.jpg
    2019-06-15 02:33:35 -- notice  -- App\Image\ImagickHandler::crop -- 80 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/997c73f21ef31f7732aaea41b6413ed1@2x.jpeg
    2019-06-15 02:33:34 -- notice  -- App\Image\ImagickHandler::crop -- 80 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/997c73f21ef31f7732aaea41b6413ed1.jpeg
    2019-06-15 02:33:34 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 106 -- Photo URL is 997c73f21ef31f7732aaea41b6413ed1.jpg
    2019-06-15 02:33:32 -- error   -- App\ModelFunctions\PhotoFunctions::save -- 489 -- Something went wrong, error 0, Array to string conversion (SQL: insert into "photos" ("id", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "public", "star", "checksum", "album_id", "owner_id", "thumb2x", "thumbUrl", "medium", "small", "updated_at", "created_at") values (15605660115242, IMG_20140725_190218, 1099b53130e0cce738e7dad34ea8d21b.jpg, , , 1944, 2592, image/jpeg, 1016.5 KB, 100, f/2.8, Samsung, Galaxy Nexus, , 59994/1000000 s, 3.4 mm, 2014-07-25 19:02:18, , , , 0, 0, ec2674c07f01e86dff48cbe82ef6ddbfc79ede8c, 15605659756842, 0, 1, 1099b53130e0cce738e7dad34ea8d21b.jpeg, 810x1080, 270x360, 2019-06-15 02:33:32, 2019-06-15 02:33:32) returning "id")
    2019-06-15 02:33:32 -- notice  -- App\Image\ImagickHandler::scale -- 46 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/small/1099b53130e0cce738e7dad34ea8d21b.jpg
    2019-06-15 02:33:32 -- notice  -- App\Image\ImagickHandler::scale -- 46 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/1099b53130e0cce738e7dad34ea8d21b.jpg
    2019-06-15 02:33:32 -- notice  -- App\Image\ImagickHandler::crop -- 80 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/1099b53130e0cce738e7dad34ea8d21b@2x.jpeg
    2019-06-15 02:33:31 -- notice  -- App\Image\ImagickHandler::crop -- 80 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/1099b53130e0cce738e7dad34ea8d21b.jpeg
    2019-06-15 02:33:31 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 106 -- Photo URL is 1099b53130e0cce738e7dad34ea8d21b.jpg
    2019-06-15 02:33:30 -- error   -- App\ModelFunctions\PhotoFunctions::save -- 489 -- Something went wrong, error 0, Array to string conversion (SQL: insert into "photos" ("id", "title", "url", "description", "tags", "width", "height", "type", "size", "iso", "aperture", "make", "model", "lens", "shutter", "focal", "takestamp", "latitude", "longitude", "altitude", "public", "star", "checksum", "album_id", "owner_id", "thumb2x", "thumbUrl", "medium", "small", "updated_at", "created_at") values (15605660092513, IMG_20140416_230210, b93d8e37c00a60cae40a143a85cf2bb6.jpg, , , 2592, 1944, image/jpeg, 878.6 KB, 640, f/2.8, Samsung, Galaxy Nexus, , 58322/1000000 s, 3.4 mm, 2014-04-16 23:02:10, , , , 0, 0, fc27e250541400d0b93f31c46e30d4664d6eed14, 15605659756842, 0, 1, b93d8e37c00a60cae40a143a85cf2bb6.jpeg, 1440x1080, 480x360, 2019-06-15 02:33:30, 2019-06-15 02:33:30) returning "id")
    2019-06-15 02:33:30 -- notice  -- App\Image\ImagickHandler::scale -- 46 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/small/b93d8e37c00a60cae40a143a85cf2bb6.jpg
    2019-06-15 02:33:30 -- notice  -- App\Image\ImagickHandler::scale -- 46 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/medium/b93d8e37c00a60cae40a143a85cf2bb6.jpg
    2019-06-15 02:33:30 -- notice  -- App\Image\ImagickHandler::crop -- 80 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/b93d8e37c00a60cae40a143a85cf2bb6@2x.jpeg
    2019-06-15 02:33:29 -- notice  -- App\Image\ImagickHandler::crop -- 80 -- Saving thumb to /var/www/html/Lychee-Laravel/public/uploads/thumb/b93d8e37c00a60cae40a143a85cf2bb6.jpeg
    2019-06-15 02:33:29 -- notice  -- App\ModelFunctions\PhotoFunctions::createThumb -- 106 -- Photo URL is b93d8e37c00a60cae40a143a85cf2bb6.jpg```

**Comment by ildyria** [comment]
@psjbeisler Can you check if this bug is still there ?
