### ISSUE TITLE
Accessing Lyche only shows folder index

### ISSUE THREAD

**Issue by avalx** [LycheeOrg/Lychee-Laravel#327]
### Detailed description of the problem
I installed Lychee as per instructions: https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install 
Everything went OK during installation/migration from my Lychee 3 version installation. But when I try to access the new Lychee page (like: http://myserver.lan/Lychee) I only got the index page of all the files like in the screenshot

### Steps to reproduce the issue
**Steps to reproduce the behavior:**
1. Install Lyche-Laravel into /var/www/html/Lychee
2. Run all commands from the installation guide
3. Go to Lyche home page like: http://myserver.lan/Lychee
4. Only see the files index page

**Screenshots**
*If applicable, add screenshots to help explain your problem.*
![image](https://user-images.githubusercontent.com/22810741/64114603-b60e8b00-cd8d-11e9-9f9b-19f66f0d4908.png)

### Output of the diagnostics
*(Settings => Diagnostics or https://example.com/Diagnostics )*

### Browser and system
Server Fedora 30, Apache http server (httpd-2.4.41-1.fc30.x86_64), PHP 7.3.8, Vivaldi or Firefox browser.

**Comment by ildyria** [comment]
Try to open the `public` folder. Your `http://myserver.lan/Lychee` should point to the content of `public` not the root of the directory.

**Comment by avalx** [comment]
OK, accessing the public folder gets me a lot of exception errors:

![www sever lan_Lychee_public_ 2019-09-02 14 40 44 www sever lan a653c178664c](https://user-images.githubusercontent.com/22810741/64115422-e48d6580-cd8f-11e9-941c-ac7eb919278a.jpg)

**Comment by ildyria** [comment]
This should be fixed by this step: https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install#3-set-storage-permissions-for-uploads

It basically says that it can't write to `storage/logs/Laravel.log`.
One of the way to solve that is to actually create the said file and then give its ownership to the server.

**Comment by avalx** [comment]
I've done that during the installation and now once again. After that the the exception went away. But now I get some server/API error:

![Lychee v4 2019-09-02 14 49 39 www sever lan badd78438ffc](https://user-images.githubusercontent.com/22810741/64115901-1d7a0a00-cd91-11e9-9a06-b3e2f43f014e.jpg)

Any idea what might be the cause for this?

**Comment by ildyria** [comment]
Yes.
Press F12, go to the network tab and refresh the page. You will see a request for `http://myserver.lan/php/index.php` this request should be `http://myserver.lan/Lychee/php/index.php`

If your `http://myserver.lan` point directly to the `public` directory you won't have this problem anymore.

**Comment by avalx** [comment]
I'm sorry I didn't quite understand what to do to resolve this. I did as you suggested and this is the result, but even after that I still get the same error.

![Lychee v4 2019-09-02 15 01 53 www sever lan fb004156b6e5](https://user-images.githubusercontent.com/22810741/64116701-53b88900-cd93-11e9-8942-b152dbfb961f.jpg)


Do I have to change something in my httpd config as well?

**Comment by ildyria** [comment]
> Do I have to change something in my httpd config as well?

I assume that `server.lan` is a `host` redirection on a lan server. As a result I would suggest you to have a look at: https://github.com/LycheeOrg/Lychee-Laravel/wiki/Install-Steps-on-Debian-(Testing)#4-getting-apache-to-run

**Comment by avalx** [comment]
I've checked that and configured Apache conf file for Lychee (without a new virtual host) and now it's working - thanks very much. :)

But I still got some errors in the Diagnostics page:

```
 Diagnostics
     -----------
     Warning: 'dist/user.css' does not exist or has insufficient read/write privileges.
     Warning: 'dist/' has insufficient read/write privileges.

``` 

So I did ` chown -R apache:apache  public/dist/` end the Warning disapeared - is this normal?

**Comment by avalx** [comment]
And there are some (old?) errors in the Show logs window:

    2019-09-02 12:41:14 -- error   -- App\Configs::get_value -- 166 -- SL_life_time_days does not exist in config (local) !
    2019-09-02 12:41:14 -- error   -- App\Configs::get_value -- 166 -- landing_page_enable does not exist in config (local) !
    2019-09-02 12:40:29 -- error   -- App\Configs::get_value -- 166 -- SL_life_time_days does not exist in config (local) !
    2019-09-02 12:40:29 -- error   -- App\Configs::get_value -- 166 -- landing_page_enable does not exist in config (local) !
    2019-09-02 12:09:50 -- error   -- App\Configs::get_value -- 166 -- SL_life_time_days does not exist in config (local) !
    2019-09-02 12:09:50 -- error   -- App\Configs::get_value -- 166 -- landing_page_enable does not exist in config (local) !
    2019-09-02 14:00:20 -- error   -- App\Configs::get_value -- 166 -- SL_life_time_days does not exist in config (local) !
    2019-09-02 14:00:20 -- error   -- App\Configs::get_value -- 166 -- landing_page_enable does not exist in config (local) !
    2019-09-02 13:50:56 -- error   -- App\Configs::get_value -- 166 -- full_photo does not exist in config (local) !
    2019-09-02 13:50:54 -- error   -- App\Configs::get_value -- 166 -- imagick does not exist in config (local) !
    2019-09-02 13:50:54 -- error   -- App\Configs::get_value -- 166 -- compression_quality does not exist in config (local) !

Is this anything to worry about?

**Comment by ildyria** [comment]
No I don't think you have anything to worry about thoses.

**Comment by avalx** [comment]
OK, thanks for all the help.
